Cosmos.Portal/Controllers/LoginController.cs
using Cosmos.DataServices;
using Cosmos.Portal.Helpers;
using System;
using System.Net;
using System.Web.Mvc;

namespace Cosmos.Portal.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult UserValidate(FormCollection fields_values)
        {
            var userID = fields_values["UserID"];
            var userPassword = fields_values["userPassword"];

            var passwordHash = Utils.HashUtil.GetSha256FromString(userPassword);
            userPassword = passwordHash;

            var user_srv = new UserDataServices();
            try
            {
                if (string.IsNullOrEmpty(userID) || string.IsNullOrEmpty(userPassword))
                    throw new Exception("Campos inválidos. Verifique.");

                var user = user_srv.UserValidate(userID, userPassword);

                if (user == null)
                    throw new Exception("Acesso negado.");

                //considerando que o objeto user retornou certo, coloco ele na sessão de uso
                SessionContext.UserData = user;

                return Json(new { result = "Redirect", url = Url.Action("Index", "Home") });
            }
            catch (Exception err)
            {
                return Json(new { result = "Fail", msg = err.Message });
            }
            finally
            {
                user_srv = null;
            }
        }

        public ActionResult LogOut()
        {
            SessionContext.UserData = null;
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

Cosmos.Portal/Views/Shared/DropDownStatus_.cshtml
@model  int

@Html.DropDownList("cboStatus",
        new SelectList(new[] {
        new {id=-1, description="Selecione um status"},
        new {id=0, description="Inativo"},
        new {id=1, description="Ativo"}
        }, "id", "description"), new
        {
            @id = "cboStatus",
            @class = "form-control"
})


<script type="text/javascript">

    $(document).ready(function ()
    {
        $('#cboStatus').attr("data-msg", "Selecione um status.");
        $('#hdStatus').val($("#cboStatus").val());
        $('#cboStatus').val('@int.Parse(@Model.ToString())');



    });

    function confirmStatus(form) {

        var selectedStatus = $('#cboStatus').val();

        //form.validate().element("#cboStatus");

        if (selectedStatus == '' || selectedStatus == undefined || selectedStatus == "-1") {
            toastr.error("Escolha um status...");
            $('#cboStatus').focus();
            return false;
        } else {
            return true;
        }

    }
</script>

Cosmos.Portal/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Cosmos - Web Portal
    </div>
    <div>
    </div>
</div>

Cosmos.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>MultiApp | @ViewBag.Title</title>

    @*<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>*@
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/plugins/toastrStyles")

    @*<style>
            #toast-container > .toast-info:before {
                /*content: "fa fa-spinner fa-spin" !important;*/
            }
        </style>*@
</head>
<body class="skin-cosmos">

    <!-- Skin configuration box -->
    <!-- @Html.Partial("_SkinConfig") -->
    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")
        </div>
        <!-- End page wrapper-->
        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")
    </div>
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    @Scripts.Render("~/bundles/inspinia")
    @Scripts.Render("~/plugins/toastr")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    @Scripts.Render("~/Scripts/fieldValidator")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "onclick": null,
            "showDuration": "10000",
            "hideDuration": "1000",
            "timeOut": "3000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut",
            "preventDuplicates": true
        }

        $(".navItem").on('click', function () {
            toastr.info("Aguarde...", "Processando");
        });

    });
</script>

Cosmos.Portal/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation" id="NavigationControl">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <di>
                    <span>

                        <img alt="Intelbras" src="~/Images/logotipo.png" style="height:2.5em" />
                    </span>
                </di>
            </li>

            <li class="@Html.IsSelected(controller: "Home")">
                <a href="@Url.Action("Index", "Home")" class="navItem"><i class="fa fa-dashboard"></i> <span class="nav-label" data-i18n="nav.dashboard">Principal</span></a>
            </li>

            <li class="@Html.IsSelected(controller: "User")">
                <a href="#"><i class="fa fa-user"></i> <span class="nav-label" data-i18n="nav.graphs">Usuários</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "User", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Novo Usuário")"><a href="@Url.Action("Form", "User")" class="navItem">Novo Usuário</a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("List", "User")" class="navItem">Listar</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Brand") requerValidacaoConfiguracoes">
                <a href="#"><i class="fa fa-drivers-license"></i> <span class="nav-label" data-i18n="nav.graphs">Montadoras</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Brand", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Cadastrar")"><a href="@Url.Action("Form", "Brand")">Nova Montadora</a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("List", "Brand")">Listar</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "TermsAndConditions") requerValidacaoConfiguracoes">
                <a href="#"><i class="fa fa-file-pdf-o"></i> <span class="nav-label" data-i18n="nav.graphs">Termos e Privacidade</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "TermsAndConditions", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Cadastrar")"><a href="@Url.Action("Form", "TermsAndConditions")">Novo Termo </a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("Index", "TermsAndConditions")">Listar</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "App") requerValidacaoConfiguracoes">
                <a href="#"><i class="fa fa-apple"></i> <span class="nav-label" data-i18n="nav.graphs">Aplicativos</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "App", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Cadastrar")"><a href="@Url.Action("Form", "App")">Novo Aplicativo</a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("List", "App")">Listar</a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("RemovedApps", "App")">Listar Inativos</a></li>
                    <li class="@Html.IsSelected(action: "SuggestionList")"><a href="@Url.Action("SuggestionList", "App")">Sugestões de Aplicativos</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Category") requerValidacaoConfiguracoes">
                <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label" data-i18n="nav.graphs">Categorias</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Category", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Cadastrar")"><a href="@Url.Action("Form", "Category")">Nova Categoria</a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("List", "Category")">Listar</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Vehicle") requerValidacaoConfiguracoes">
                <a href="#"><i class="fa fa-car"></i> <span class="nav-label" data-i18n="nav.graphs">Veículos</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Vehicle", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Cadastrar")"><a href="@Url.Action("Form", "Vehicle")">Novo Veículo</a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("List", "Vehicle")">Listar</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "SO") requerValidacaoConfiguracoes">
                <a href="#"><i class="fa fa-car"></i> <span class="nav-label" data-i18n="nav.graphs">SO</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "SO", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Cadastrar")"><a href="@Url.Action("Form", "SO")">Novo SO</a></li>
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("List", "SO")">Listar</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Message") requerValidacaoConfiguracoes">
                <a href="#"><i class="fa fa-car"></i> <span class="nav-label" data-i18n="nav.graphs">Mensagens</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Message", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "Listar")"><a href="@Url.Action("List", "Message")">Listar</a></li>
                </ul>
            </li>
            @* }*@
        </ul>
    </div>
</nav>

@Scripts.Render("~/bundles/jquery")

<script>

    $(document).ready(function () {

    });
</script>

Cosmos.Portal/Views/Shared/_PVDashBoard.cshtml
<div id="etabs-tab-container" class="etabs-tab-container">
    <ul class='etabs'>
        <li class='etabs-tab'><a href="#tabDiario">Diário</a></li>
        <li class='etabs-tab'><a href="#tabMensal">Mensal</a></li>
    </ul>
    <div class="etabs-panel-container">

        <div id="tabDiario" style="padding:20px">

            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-crosshairs"></i>
                        </div>
                        <a href="#" class="forum-item-title"> Total de Ocorrências sem direcionamento</a>
                        <div class="forum-sub-title">Ocorrências que forma abertas, mas que ainda não foram direcionadas ao atendimento.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.SemDirecionamento.ToString()</strong>
                        </span>

                    </div>
                </div>
            </div>

            <div class="forum-item active">

                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-bullhorn"></i>
                        </div>
                        <a href="#" class="forum-item-title"> Total de Ocorrências Abertas</a>
                        <div class="forum-sub-title">Ocorrências que forma abertas no CRM.</div>

                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.Abertas.ToString()</strong>
                        </span>

                    </div>
                </div>
            </div>

            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-flag-checkered"></i>
                        </div>
                        <a href="#" class="forum-item-title">Total de Ocorrências Fechadas</a>
                        <div class="forum-sub-title">Ocorrências já atendidas pelos técnicos.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.Fechadas.ToString()</strong>
                        </span>

                    </div>
                </div>
            </div>

            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-bullseye"></i>
                        </div>
                        <a href="#" class="forum-item-title">Total de Ocorrências Dentro do SLA</a>
                        <div class="forum-sub-title">Ocorrências atendidas dentro do tempo esperado no SLA.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.DentroSLA.ToString()</strong>
                        </span>

                    </div>
                </div>
            </div>

            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-ambulance"></i>
                        </div>
                        <a href="#" class="forum-item-title">Total de Ocorrências Fora do SLA</a>
                        <div class="forum-sub-title">Ocorrências que não foram atendidas dentro do prazo estipulado no SLA.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.ForaSLA.ToString()</strong>
                        </span>

                    </div>
                </div>
            </div>
        </div>

        <div id="tabMensal" style="padding:20px">
            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-crosshairs"></i>
                        </div>
                        <a href="#" class="forum-item-title"> Total de Ocorrências sem direcionamento</a>
                        <div class="forum-sub-title">Ocorrências que forma abertas, mas que ainda não foram direcionadas ao atendimento.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.SemDirecionamento.ToString()</strong>
                        </span>

                    </div>
                </div>
            </div>

            <div class="forum-item active">

                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-bullhorn"></i>
                        </div>
                        <a href="#" class="forum-item-title"> Total de Ocorrências Abertas</a>
                        <div class="forum-sub-title">Ocorrências que forma abertas no CRM.</div>

                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.Abertas.ToString()</strong>
                        </span>

                    </div>
                </div>
            </div>

            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-flag-checkered"></i>
                        </div>
                        <a href="#" class="forum-item-title">Total de Ocorrências Fechadas</a>
                        <div class="forum-sub-title">Ocorrências já atendidas pelos técnicos.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.Fechadas.ToString()</strong>
                        </span>
                    </div>
                </div>
            </div>

            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-bullseye"></i>
                        </div>
                        <a href="#" class="forum-item-title">Total de Ocorrências Dentro do SLA</a>
                        <div class="forum-sub-title">Ocorrências atendidas dentro do tempo esperado no SLA.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.DentroSLA.ToString()</strong>
                        </span>
                    </div>
                </div>
            </div>

            <div class="forum-item active">
                <div class="row">
                    <div class="col-md-9">
                        <div class="forum-icon">
                            <i class="fa fa-ambulance"></i>
                        </div>
                        <a href="#" class="forum-item-title">Total de Ocorrências Fora do SLA</a>
                        <div class="forum-sub-title">Ocorrências que não foram atendidas dentro do prazo estipulado no SLA.</div>
                    </div>

                    <div class="col-md-1 forum-info pull-right">
                        <span class="views-number">
                            <strong>@Model.MonthlySum.ForaSLA.ToString()</strong>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Cosmos.Portal/Views/Shared/_SkinConfig.cshtml
<div class="theme-config">
    <div class="theme-config-box">
        <div class="spin-icon">
            <i class="fa fa-cogs fa-spin"></i>
        </div>
        <div class="skin-setttings">
            <div class="title">Configuration</div>
            <div class="setings-item">
                <span>
                    Collapse menu
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                        <label class="onoffswitch-label" for="collapsemenu">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed sidebar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedsidebar" class="onoffswitch-checkbox" id="fixedsidebar">
                        <label class="onoffswitch-label" for="fixedsidebar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                        <label class="onoffswitch-label" for="fixednavbar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar v.2
                    <br />
                    <small>*Primary layout</small>
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar2" class="onoffswitch-checkbox" id="fixednavbar2">
                        <label class="onoffswitch-label" for="fixednavbar2">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Boxed layout
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                        <label class="onoffswitch-label" for="boxedlayout">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed footer
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedfooter" class="onoffswitch-checkbox" id="fixedfooter">
                        <label class="onoffswitch-label" for="fixedfooter">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="title">Skins</div>
            <div class="setings-item default-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-0">
                        Default
                    </a>
                </span>
            </div>
            <div class="setings-item blue-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-1">
                        Blue light
                    </a>
                </span>
            </div>
            <div class="setings-item yellow-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-3">
                        Yellow/Purple
                    </a>
                </span>
            </div>
            <div class="setings-item ultra-skin">
                <span class="skin-name ">
                    <a target="_blank" href="md_skin/" class="md-skin">
                        Material Design
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

Cosmos.Portal/Views/Shared/_SpinnerControl.cshtml
<div class="spiner-example" id="processingContainer" style="width:100%;height:100%;z-index:100000;position:absolute;background-color:rgba(13, 81, 25, 0.0);">
    <div class="sk-spinner  sk-spinner-fading-circle" style="width:60px;height:60px;position:absolute;bottom:10%;left:48%;text-align:center;">
        <div class="sk-circle1 sk-circle"></div>
        <div class="sk-circle2 sk-circle"></div>
        <div class="sk-circle3 sk-circle"></div>
        <div class="sk-circle4 sk-circle"></div>
        <div class="sk-circle5 sk-circle"></div>
        <div class="sk-circle6 sk-circle"></div>
        <div class="sk-circle7 sk-circle"></div>
        <div class="sk-circle8 sk-circle"></div>
        <div class="sk-circle9 sk-circle"></div>
        <div class="sk-circle10 sk-circle"></div>
        <div class="sk-circle11 sk-circle"></div>
        <div class="sk-circle12 sk-circle"></div>
    </div>
</div>

Cosmos.Portal/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                @try
                {
                    @(Cosmos.Portal.Helpers.SessionContext.UserData.Name)

                }
                catch (Exception ex)
                {
                    Response.Redirect("~/ErrorHandler/Index");
                }
            </li>
            <li>
                <a href="@Url.Action("Index", "Login")" style="color:#fff !important" id="btLogOut">
                    <i class="fa fa-sign-out"></i> Sair
                </a>
            </li>
        </ul>
    </nav>
</div>
@section Scripts {

    @Scripts.Render("~/bundles/jquery")

    <script>
        $(document).ready(function () {
            $('#btLogOut').on('click', function () {
                $.ajax({
                    type: "GET",
                    url: '/Login/Logout',
                    success: function (response) {
                        window.location = "/Login/Index";
                    }
                })
            });
        });
    </script>
}