Cosmos.Portal/Controllers/AppVersionController.cs
using Cosmos.Portal.ViewModel;
using Cosmos.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cosmos.Portal.Controllers
{
    public class AppVersionController : Controller
    {
        private static AppViewModel _viewmodels = new AppViewModel();

        // GET: AppVersion
        public ActionResult Add(string AppId)
        {
            var viewmodel = new AppViewModel();

            try
            {
                viewmodel.app = new DataServices.AppStoreDataServices().GetApplicationById(AppId);
                _viewmodels = viewmodel;
            }
            catch (Exception err)
            {
                new ErrorHandlerController().redirectToErrorPage(err.Message);
            }
            finally
            {
            }

            return View(viewmodel);
        }

        public ActionResult Edit(string VersionID)
        {
            var viewmodel = new AppViewModel();

            try
            {
                viewmodel.appVersion = new DataServices.AppVersionDataServices().GetAppVersionById(VersionID);
                _viewmodels = viewmodel;
            }
            catch (Exception err)
            {
                new ErrorHandlerController().redirectToErrorPage(err.Message);
            }
            finally
            {
            }

            return View(viewmodel);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update(AppViewModel viewmodel)
        {
            try
            {
                _viewmodels.appVersion.ReleaseNote = viewmodel.appVersion.ReleaseNote;
                _viewmodels.appVersion.ReleaseNoteES = viewmodel.appVersion.ReleaseNoteES;
                _viewmodels.appVersion.ReleaseNoteEN = viewmodel.appVersion.ReleaseNoteEN;
                _viewmodels.appVersion.Version = viewmodel.appVersion.Version;
                new DataServices.AppVersionDataServices().Update(_viewmodels.appVersion);

                return RedirectToAction("Profile", "App", new { Appid = _viewmodels.appVersion.ApplicationId });
            }
            catch (Exception)
            {
                return View(viewmodel);
            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Add(AppViewModel viewmodel)
        {
            try
            {
                viewmodel.app = _viewmodels.app;
                viewmodel.appVersion.ApkSize = viewmodel.appVersion.ApkData.ContentLength;

                if (viewmodel.appVersion.ApkData == null)
                    throw new Exception("Escolha um arquivo APK para a publicação do seu aplicativo.");
                var apkUrl = BlobConnector.UploadFile(viewmodel.appVersion.ApkData, "apks");
                if (string.IsNullOrEmpty(apkUrl))
                    throw new Exception("Erro ao fazer o upload do apk");
                viewmodel.appVersion.ApkUri = apkUrl;
                viewmodel.appVersion.Status = true;
                viewmodel.appVersion.ReleaseDate = DateTime.Parse(string.Format("{0:yyyy/MM/dd HH:mm:ss.fff}", DateTime.Now));
                viewmodel.appVersion.Package = viewmodel.app.PackageName;
                viewmodel.appVersion.ApplicationId = viewmodel.app.Id;
                new DataServices.AppVersionDataServices().AddNewVersion(viewmodel.appVersion);
                return RedirectToAction("Profile", "App", new { Appid = _viewmodels.app.Id });
            }
            catch (Exception)
            {
                return View(viewmodel);
            }
        }
    }
}

Cosmos.Portal/Views/AppVersion/Add.cshtml
@model Cosmos.Portal.ViewModel.AppViewModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row wrapper">
            <div class="col-sm-8">
                <h2>Aplicativos</h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="@Url.Action("Index", "Home")">Principal</a>
                    </li>
                    <li>
                        <a href="@Url.Action("List", "App")">Lista de Aplicativos</a>
                    </li>
                    <li class="active">
                        <strong>Nova Versão do Aplicativo</strong>
                    </li>
                </ol>
            </div>
        </div>
        @using (Ajax.BeginForm("Add", "AppVersion",
                     new AjaxOptions
                     {
                         HttpMethod = "POST"
                     },
                     new
                     {
                         enctype = "multipart/form-data",
                         @class = "form-horizontal"
                     }))
        {
            <form>
                <div class="form-group" style=" margin-top:1.5em">
                    @Html.Label("Version Name", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.appVersion.Version, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @required = "required"
                       }
                   })
                        @Html.ValidationMessageFor(model => model.appVersion.Version, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.appVersion.VersionCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.appVersion.VersionCode, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @required = "required"
                       }
                   })
                        @Html.ValidationMessageFor(model => model.appVersion.VersionCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Release Note", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.appVersion.ReleaseNote, new { style="width: 100%" , @class = "form-control col-md-2"} )
                        @Html.ValidationMessageFor(model => model.appVersion.ReleaseNote, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Release Note Em Espanhol", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.appVersion.ReleaseNoteES, new { style = "width: 100%", @class = "form-control col-md-2" })
                        @Html.ValidationMessageFor(model => model.appVersion.ReleaseNoteES, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Release Note em Inglês", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.appVersion.ReleaseNoteEN, new { style = "width: 100%", @class = "form-control col-md-2" })
                        @Html.ValidationMessageFor(model => model.appVersion.ReleaseNoteEN, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Apk", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.appVersion.ApkData,
                                             new
                                             {
                                                 @class = "form-control space",
                                                 @accept = ".apk",
                                                 @type = "file",
                                                 @required = "required"
                                             })
                        @Html.ValidationMessageFor(model => model.appVersion.ApkData, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </form>
        }
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cosmos.Portal/Views/AppVersion/Edit.cshtml
@model Cosmos.Portal.ViewModel.AppViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row wrapper">
    <div class="col-sm-8">
        <h2>Aplicativos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Principal</a>
            </li>
            <li>
                <a href="@Url.Action("List", "App")">Lista de Aplicativos</a>
            </li>
            <li class="active">
                <strong>Editar versão do Aplicativo</strong>
            </li>
        </ol>
    </div>
</div>

@using (Ajax.BeginForm("Update", "AppVersion",
                      new AjaxOptions
                      {
                          HttpMethod = "POST"
                      },
                      new
                      {
                          enctype = "multipart/form-data",
                          @class = "form-horizontal"
                      }))
{
    <form>
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.appVersion.Id)


            <div class="form-group">
                @Html.Label("Version Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.appVersion.Version, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.appVersion.Version, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Release Note", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.appVersion.ReleaseNote, new { style = "width: 100%", @class = "form-control col-md-2" })
                    @Html.ValidationMessageFor(model => model.appVersion.ReleaseNote, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Release Note em Espanhol", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.appVersion.ReleaseNoteES, new { style = "width: 100%", @class = "form-control col-md-2" })
                    @Html.ValidationMessageFor(model => model.appVersion.ReleaseNoteES, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Release Note em Inglês", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.appVersion.ReleaseNoteEN, new { style = "width: 100%", @class = "form-control col-md-2" })
                    @Html.ValidationMessageFor(model => model.appVersion.ReleaseNoteEN, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </form>
}