Cosmos.Portal/Controllers/TermsAndConditionsController.cs
using Cosmos.Log;
using Cosmos.Portal.ViewModel;
using Cosmos.Services.Interfaces;
using Cosmos.Utils;
using System;
using System.Web.Mvc;

namespace Cosmos.Portal.Controllers
{
    public class TermsAndConditionsController : Controller
    {
        private readonly ITermsAndConditionsService _termsAndConditionsService;
        private static TermsAndConditionsViewModel _viewModel = new TermsAndConditionsViewModel();

        public TermsAndConditionsController(ITermsAndConditionsService termsAndConditionsService)
        {
            _termsAndConditionsService = termsAndConditionsService;
        }

        public ActionResult Delete(Guid Id)
        {
            _viewModel.TermAndCondition = _viewModel.TermsAndConditions.Find(s => s.Id == Id);

            return View(_viewModel);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete(TermsAndConditionsViewModel viewModel)
        {
            _viewModel.TermAndCondition.Status = false;
            _termsAndConditionsService.Update(_viewModel.TermAndCondition);
            return RedirectToAction("Index");
        }

        public ActionResult Active(Guid Id)
        {
            _viewModel.TermAndCondition = _viewModel.TermsAndConditions.Find(s => s.Id == Id);

            return View(_viewModel);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Active(TermsAndConditionsViewModel viewModel)
        {
            _termsAndConditionsService.Active(_viewModel.TermAndCondition);
            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            TermsAndConditionsViewModel viewmodel = new TermsAndConditionsViewModel();

            try
            {
                viewmodel.TermsAndConditions = _termsAndConditionsService.GetTermsAndConditions();
                _viewModel = viewmodel;
            }
            catch (Exception err)
            {
                new ErrorHandlerController().redirectToErrorPage(err.Message);
            }

            return View(viewmodel);
        }

        public ActionResult Form()
        {
            TermsAndConditionsViewModel viewmodel = new TermsAndConditionsViewModel();
            try
            {
                viewmodel.Brands = new DataServices.BrandDataServices().GetAll();
            }
            catch (Exception err)
            {
                new ErrorHandlerController().redirectToErrorPage(err.Message);
            }
            finally
            {
            }

            return View(viewmodel);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Add(TermsAndConditionsViewModel viewmodel)
        {
            try
            {
                viewmodel.TermAndCondition.FilePT = BlobConnector.UploadFile(viewmodel.TermAndCondition.PDFPT, "terms");

                if (string.IsNullOrEmpty(viewmodel.TermAndCondition.FilePT))
                {
                    throw new Exception("Erro ao fazer o upload do pdf em português!");
                }
                viewmodel.TermAndCondition.FileEN = BlobConnector.UploadFile(viewmodel.TermAndCondition.PDFEN, "terms");

                if (string.IsNullOrEmpty(viewmodel.TermAndCondition.FileEN))
                {
                    throw new Exception("Erro ao fazer o upload do pdf em inglês!");
                }
                viewmodel.TermAndCondition.FileES = BlobConnector.UploadFile(viewmodel.TermAndCondition.PDFES, "terms");

                if (string.IsNullOrEmpty(viewmodel.TermAndCondition.FileES))
                {
                    throw new Exception("Erro ao fazer o upload do pdf em espanhol!");
                }
                viewmodel.TermAndCondition.Register = DateTime.Now;
                _termsAndConditionsService.Insert(viewmodel.TermAndCondition);
                return RedirectToAction("Index");
            }
            catch (Exception err)
            {
                new NLogExceptionLogger().Log("TermsAndConditions - Add" + err.Message, Model.LogType.Error);
                return View(viewmodel);
            }
            finally
            {
            }
        }
    }
}

Cosmos.Portal/Views/TermsAndConditions/Active.cshtml
@model Cosmos.Portal.ViewModel.TermsAndConditionsViewModel

@{
    ViewBag.Title = "Active";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper">
    <div class="col-sm-8">
        <h2>Aplicativos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Principal</a>
            </li>
            <li>
                <a href="@Url.Action("List", "TermsAndConditions")">Termos e Condições</a>
            </li>
            <li class="active">
                <strong>Ativar Termo</strong>
            </li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content" style="background-color:transparent!important; border:none!important;margin-top:1.5em">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group row">
                        <div style="display: inline-block; margin-left: 1%;">
                            <h3>Deseja Ativar o termo?</h3>
                        </div>
                    </div>
                    <hr />

                    <div style="display: inline-block; margin-left: 1%;">
                        <h3>@Model.TermAndCondition.TitlePT</h3>
                    </div>
                    <hr />

                    <hr />

                    <dl class="dl-horizontal"></dl>

                    <div class="form-actions no-color">
                        <input type="submit" value="Ativar" class="btn btn-primary" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Cosmos.Portal/Views/TermsAndConditions/Delete.cshtml
@model Cosmos.Portal.ViewModel.TermsAndConditionsViewModel


@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper">
    <div class="col-sm-8">
        <h2>Aplicativos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Principal</a>
            </li>
            <li>
                <a href="@Url.Action("List", "TermsAndConditions")">Termos e Condições</a>
            </li>
            <li class="active">
                <strong>Remover Termo</strong>
            </li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content" style="background-color:transparent!important; border:none!important;margin-top:1.5em">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group row">
                        <div style="display: inline-block; margin-left: 1%;">
                            <h3>Deseja remover o termo?</h3>
                        </div>
                    </div>
                    <hr />

                    <div style="display: inline-block; margin-left: 1%;">
                        <h3>@Model.TermAndCondition.TitlePT</h3>
                    </div>
                    <hr />

                    <hr />

                    <dl class="dl-horizontal"></dl>


                    <div class="form-actions no-color">
                        <input type="submit" value="Remover" class="btn btn-danger" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Cosmos.Portal/Views/TermsAndConditions/Form.cshtml
@model Cosmos.Portal.ViewModel.TermsAndConditionsViewModel

@{
    ViewBag.Title = "Termos e Privacidade";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Termos e Privacidade</h2>

@using (Ajax.BeginForm("Add", "TermsAndConditions",
              new AjaxOptions
              {
                  HttpMethod = "POST"
              },
              new
              {
                  enctype = "multipart/form-data",
                  @class = "form-horizontal"
              }))
{
    <form>
        <div class="form-horizontal">
            <h4>Adicionar novo</h4>
            <hr />

            <div class="form-group">
                @Html.Label("Título ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TermAndCondition.TitlePT, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.TermAndCondition.TitlePT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Título em Inglês", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TermAndCondition.TitleEN, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.TermAndCondition.TitleEN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Título em Espanhol", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TermAndCondition.TitleES, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.TermAndCondition.TitleES, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Montadora", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.TermAndCondition.IdBrand, new SelectList(Model.Brands, "Id", "Name"), "Selecione a Montadora", new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.TermAndCondition.IdBrand, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("PDF em portugês", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.TermAndCondition.PDFPT, new { @class = "form-control", @accept = ".pdf", @type = "file", @required = "required" })
                    @Html.ValidationMessageFor(model => model.TermAndCondition.PDFPT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("PDF em Inglês", htmlAttributes: new { @class = "control-label col-md-2", @required = "required" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.TermAndCondition.PDFEN, new { @class = "form-control", @accept = ".pdf", @type = "file", @required = "required" })
                    @Html.ValidationMessageFor(model => model.TermAndCondition.PDFEN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("PDF em Espanhol", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.TermAndCondition.PDFES, new { @class = "form-control", @accept = ".pdf", @type = "file", @required = "required" })
                    @Html.ValidationMessageFor(model => model.TermAndCondition.PDFES, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
}
<div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cosmos.Portal/Views/TermsAndConditions/Index.cshtml
@model Cosmos.Portal.ViewModel.TermsAndConditionsViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Adicionar Novo", "Form")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Versão")
        </th>
        <th>
            @Html.DisplayName("Titulo")
        </th>
        <th>
            @Html.DisplayName("Montadora")
        </th>
        <th>
            @Html.DisplayName("Data")
        </th>
        <th>
            @Html.DisplayName("PDF")
        </th>
        <th>
            @Html.DisplayName("Concordaram")
        </th>
        <th>
            @Html.DisplayName("Rejeitaram")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.TermsAndConditions)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Version)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TitlePT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Register)
        </td>
        <td>
            <button type="button" class="btn btn-primary btn-xs" value="Download" onclick="location.href='@item.FilePT'">Download
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Accepteds)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Recuseds)
        </td>
        <td class="text-center">
            @if (item.Active == false)
            {
                @Html.ActionLink("Ativar", "Active", new { id = @item.Id }, new { @class = "btn btn-primary btn-xs" }) @Html.ActionLink("Deletar", "Delete", new { id = @item.Id }, new { @class = "btn btn-danger btn-xs" })
            }
        </td>
    </tr>
    }
</table>