Cosmos.Portal/Controllers/PasswordResetController.cs
using System;
using System.Net;
using System.Web.Mvc;
using Cosmos.DataServices;
using Cosmos.Model;
using Cosmos.Portal.Helpers;

namespace Cosmos.Portal.Controllers
{
    public class PasswordResetController : Controller
    {
        private static string token;

        private static PasswordReset user;
        // GET: PasswordReset
        public ActionResult Index()
        {
            TempData["msg"] = "false";
            if (Request.QueryString["t"] != null)
            {
                token = Request.QueryString["t"].ToString();
                user = new DataServices.PasswordResetDataServices().GetByToken(token);
                if (user != null) 
                    TempData["msg"] = "true";
            }
            return View();
        }
        [HttpPost]
        public JsonResult Update(FormCollection viewmodel)
        {
            var password = viewmodel["password"];
            try
            {
                var userId = new DataServices.PasswordResetDataServices().GetByToken(token);
                if (userId == null)
                {
                    return Json(new { result = "Fail", msg = "Token Inválido!" });
                }
                var user = new DataServices.UserDataServices().GetUserById(userId.UserId);
                user.Password = Utils.HashUtil.GetSha256FromString(password);
                if (new DataServices.UserDataServices().UpdateUserPassword(user))
                {
                    userId.Status = false;
                    var t = new DataServices.PasswordResetDataServices().UpdateTokenStatus(userId);
                 
                    return Json(new {result = "Ok", msg = "Sua Senha foi cadastrada"});
                }
            }
            catch (Exception err)
            {
                new ErrorHandlerController().redirectToErrorPage(err.Message);
            }

            return Json(new { result = "Fail", msg = "Usuário não pode ser atualizado" });

        }
    }
}

Cosmos.Portal/Views/PasswordReset/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MultiApp | Reset de Senha</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Fonts/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/Content/animate.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet">
    <link href="~/Content/login.css" rel="stylesheet" />
    <link href="~/Content/plugins/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/ladda/ladda.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/vegas-slideshow/vegas.css" rel="stylesheet" />
    <style>
        input::-webkit-input-placeholder {
            color: white !important;
        }

        html, body {
            height: auto !important;
            background-color: transparent !important;
        }
    </style>

</head>

<body>

    <div class="middle-box text-center loginscreen  animated fadeInDown" style="background-color:rgba(255, 255, 255, 0.20); border-radius: 25px;margin-top:5em">
        <div>

            <img src="../Images/logotipo.png" />

            @{Html.BeginForm("Update", "PasswordReset", FormMethod.Post, new { @id = "frmLogin" });}

            <div class="login-container">
                <div class="form-group row">

                    <div class="col-md-10 col-sm-offset-1">
                        <input type="password" id="password" class="login-input-field" placeholder="Senha" required="" autocomplete="Senha" name="password">
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-sm-10 col-sm-offset-1">
                        <input type="password" id="passwordConfirm" class="login-input-field" required="" autocomplete="passwordConfirm" placeholder="Confirmação Senha" name="passwordConfirm">
                    </div>
                </div>

                <div class="form-group row" id="divAlert" style="display: none"  >

                    <div class="col-sm-10 col-sm-offset-1">
                        <p id="confirm"  class="login-input-field confim-text">Senha Alterada com Sucesso </p>

                    </div>
                </div>

                <div class="login-button-submit">
                    <button data-color="green" type="button" class="ladda-button ladda-button-demo btn btn-danger submitButton" data-style="expand-right">Cadastrar Senha</button>
                </div>

            </div>

            @{Html.EndForm();}

        </div>
    </div>
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/plugins/toastr/toastr.min.js"></script>
    <script src="~/Scripts/plugins/ladda/spin.min.js"></script>
    <script src="~/Scripts/plugins/ladda/ladda.min.js"></script>
    <script src="~/Scripts/plugins/ladda/ladda.jquery.min.js"></script>
    <script src="~/Scripts/plugins/jquery.countdown-2.1.0/jquery.countdown.js"></script>
    <script src="~/Content/plugins/vegas-slideshow/vegas.js"></script>

</body>

</html>
<script>

    $(document).ready(function ()
    {
        $("#password").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                // Allow: Ctrl+A, Command+A
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) || 
                // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });
        $("#passwordConfirm").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                // Allow: Ctrl+A, Command+A
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) || 
                // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        //console.log(@TempData);
        $('body').vegas(

            {
                slide: 0,
                delay: 5000,
                loop: true,
                preload: false,
                preloadImage: false,
                preloadVideo: false,
                timer: true,
                overlay: false,
                autoplay: true,
                shuffle: false,
                cover: true,
                color: null,
                align: 'center',
                valign: 'center',
                firstTransition: null,
                firstTransitionDuration: null,
                transition: 'fade',
                transitionDuration: 1000,
                transitionRegister: [],
                animation: null,
                animationDuration: 'auto',
                animationRegister: [],
                init: function () { },
                play: function () { },
                pause: function () { },
                walk: function () { },
                slides:
                [
                    { src: '../Images/gallery/car1.png' },
                    { src: '../Images/gallery/car2.png' }
                ]
            }
        );

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "onclick": null,
            "showDuration": "200",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        var l = $('.submitButton').ladda();

        l.click(function ()
        {
          //  l.ladda('start');
            $("#frmLogin").submit();
        });
        var tokenValid = @TempData["msg"];
        console.log(tokenValid);
        if (tokenValid == false) {
            toastr.error('Token Inválido', "Validação de Acesso");
            $('.submitButton').prop('disabled', true);

        }
        $("#frmLogin").on("submit", function (event) {
            $('#divAlert').css('display', 'block');
            event.preventDefault();

            var url = $(this).attr("action");
            var formData = $(this).serialize();
            var password = $('#password').val();
            if (password == '') {
                toastr.error("Digite um password válido!", "Validação de Acesso");
                return;
            }


            if (password.lenght > 6) {
                toastr.error("Digite um password válido, o password precisa ter mais de 6 caracteres!", "Validação de Acesso");
                return;
            }
            var confirmPassword = $('#passwordConfirm').val();
            if (password == confirmPassword) {
                $.ajax({
                    url: url,
                    type: "POST",
                    data: formData,
                    dataType: "json",
                    success: function (response) {
                        //l.ladda('stop');
                        if (response.result == 'Ok') {
                            toastr.success("Senha Alterada com Sucesso", "Validação de Acesso");
                            $('.submitButton').prop('disabled', true);
//                            window.location = response.url;
                        } else {
                            toastr.error(response.msg, "Validação de Acesso");
                        }
                    },
                    error: function (response) {
                        //l.ladda('stop');
                        console.log(response);
                        toastr.error("Não foi possível se comunicar com o servidor.", "Validação de Acesso");

                    }
                });
            } else {
                alert('As Senhas precisam ser iguais', 'Erro');
            }
          
        });
    });
</script>